Make the Xonotic maps no longer exempt of the sRGB requirement, now that all fulfill it. YIIIEEEEAAAAAHHH!!1

diff --git a/misc/tools/xonotic-map-compiler-autobuild b/misc/tools/xonotic-map-compiler-autobuild
--- a/misc/tools/xonotic-map-compiler-autobuild
+++ b/misc/tools/xonotic-map-compiler-autobuild
@@ -184,36 +184,21 @@ buildthemap()
 		is_nosrgb=false
 	fi
 	allow_build=true
-	case "$M" in
-		afterslime|dance|drain|glowplant|leave_em_behind|newtonian-nightmare|nexballarena|oilrig|red-planet|runningmanctf|runningman|space-elevator|stormkeep|techassault|xoylent)
-			if $is_nosrgb; then
+	if $is_nosrgb; then
+		case "$REFNAME" in
+			master|refs/heads/master|origin/master|refs/remotes/origin/master)
 				if [ -n "$IRCSPAM" ]; then
-					echo "8NOTE: map $M still uses -nosRGB. This should eventually get fixed." | $IRCSPAM || true
+					echo "4ERROR: map $M uses -nosRGB. This is not acceptable in master. Please fix." | $IRCSPAM || true
 				fi
-			else
+				allow_build=false
+				;;
+			*)
 				if [ -n "$IRCSPAM" ]; then
-					echo "9CONGRATULATIONS: map $M does not use -nosRGB any more. Please remove the map name from the list in xonotic-map-compiler-autobuild once this is merged to master." | $IRCSPAM || true
+					echo "4WARNING: map $M uses -nosRGB. This is not acceptable in master. Please fix." | $IRCSPAM || true
 				fi
-			fi
-			;;
-		*)
-			if $is_nosrgb; then
-				case "$REFNAME" in
-					master|refs/heads/master|origin/master|refs/remotes/origin/master)
-						if [ -n "$IRCSPAM" ]; then
-							echo "4ERROR: map $M uses -nosRGB. This is not acceptable in master. Please fix." | $IRCSPAM || true
-						fi
-						allow_build=false
-						;;
-					*)
-						if [ -n "$IRCSPAM" ]; then
-							echo "4WARNING: map $M uses -nosRGB. This is not acceptable in master. Please fix." | $IRCSPAM || true
-						fi
-						;;
-				esac
-			fi
-			;;
-	esac
+				;;
+		esac
+	fi
 
 	set +e
 	$allow_build && (
